SPT-767 Made Mitigating validFrom datetime
govuk-one-login/data-vocab pull request #99
Opened 2024-04-15 16:05 UTC by chris-dco

## What

Updated MitigatingCredentialClass.validFrom field to `datetime`.

## Why

CIMIT is required to produce `validFrom` in ISO time and date format. So the `validFrom` field needs to be changed to datetime.

2024-04-15 16:13 UTC, chrisclayson approved these changes, later dismissed
Wish your IDE would stop re-formatting things ... granted just getting rid of whitespace.

2024-04-15 16:22 UTC, galund requested changes
Please at least make the whitespace changes in a different commit otherwise you break the git history for those lines. Right now it's not actually clear to me what this change is actually _doing_.

2024-04-16 08:08 UTC, chris-dco commented
> Please at least make the whitespace changes in a different commit otherwise you break the git history for those lines. Right now it's not actually clear to me what this change is actually _doing_.

@chrisclayson @galund If you click on the gear, Hide Whitespace and Apply and reload you can easily see the none whitespaces changes which have been made.

![github com_govuk-one-login_data-vocab_pull_99_files_diff=split w=1](https://github.com/govuk-one-login/data-vocab/assets/122806395/830e0c0c-315f-4e96-bdef-76b66e9473be)

2024-04-16 08:10 UTC, chris-dco commented
> Wish your IDE would stop re-formatting things ... granted just getting rid of whitespace.

Sorry I've had too many PR's rejected as I have inserted whitespaces and I understand our coding standards require us to not add whitespaces.

2024-04-16 09:07 UTC, galund commented
> > Please at least make the whitespace changes in a different commit otherwise you break the git history for those lines. Right now it's not actually clear to me what this change is actually _doing_.
> 
> @chrisclayson @galund If you click on the gear, Hide Whitespace and Apply and reload you can easily see the none whitespaces changes which have been made. Alternatively click on this link which will do it for you https://github.com/govuk-one-login/data-vocab/pull/99/files?diff=split&w=1.
> 
> ![github com_govuk-one-login_data-vocab_pull_99_files_diff=split w=1](https://private-user-images.githubusercontent.com/122806395/322758712-830e0c0c-315f-4e96-bdef-76b66e9473be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTg2NDcsIm5iZiI6MTcxMzI1ODM0NywicGF0aCI6Ii8xMjI4MDYzOTUvMzIyNzU4NzEyLTgzMGUwYzBjLTMxNWYtNGU5Ni1iZGVmLTc2YjY2ZTk0NzNiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwOTA1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTdiZWZmOTU4YzAyYzM2Njc2YTEwZGNhMDU2N2VlZDkzYzFkZDE3M2ZkOWUzMjhmMmYyNzkwMDA1N2Y1ZWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tuMT5U5JSf7DfuZ874zp2k1kis9CY1WmWN3v7GzyenM)

That's true but the point is that the Git history is useful. For YAML files especially (where trailing whitespace is *significant*) it's very much worth doing this as a separate commit please. Suggest you adjust your editor for YAML as automatically trimming whitespace can actually have unwanted effects!

2024-04-16 16:06 UTC, chris-dco commented
> That's true but the point is that the Git history is useful. For YAML files especially (where trailing whitespace is _significant_) it's very much worth doing this as a separate commit please. Suggest you adjust your editor for YAML as automatically trimming whitespace can actually have unwanted effects!

@galund Reverted whitespace changes.

2024-04-16 16:21 UTC, galund reviewed
Can we get an example put into the `v1/examples` directory, and then get that validated in the tests?

Then we'd probably catch this kind of thing sooner - and we can easily check that the example matches the one in the RFC over here: https://github.com/govuk-one-login/architecture/blob/main/rfc/0041-CI-mitigation-VC.md

thanks!

2024-04-22 14:29 UTC, chris-dco commented
> Can we get an example put into the `v1/examples` directory, and then get that validated in the tests?
> 
> Then we'd probably catch this kind of thing sooner - and we can easily check that the example matches the one in the RFC over here: https://github.com/govuk-one-login/architecture/blob/main/rfc/0041-CI-mitigation-VC.md
> 
> thanks!

@galund @chrisclayson Added example and tests.

2024-04-22 14:52 UTC, galund approved these changes

2024-04-22 15:36 UTC, merged